/**************************************************
 * Copyright (c) 2021 Amanch Esmailzadeh
 * See LICENSE for details
 **************************************************/

#ifndef KAI_KEYBOARD_H
#define KAI_KEYBOARD_H

#include "types.h"

namespace kai {
    enum class Key : Uint32 {
        none = 0,
        a,
        b,
        c,
        d,
        e,
        f,
        g,
        h,
        i,
        j,
        k,
        l,
        m,
        n,
        o,
        p,
        q,
        r,
        s,
        t,
        u,
        v,
        w,
        x,
        y,
        z,
        one,
        two,
        three,
        four,
        five,
        six,
        seven,
        eight,
        nine,
        zero,
        enter,
        escape,
        backspace,
        tab,
        space,
        minus,
        equals,
        left_bracket,
        right_bracket,
        backslash,
        non_us_hash,
        semicolon,
        apostrophe,
        tilde,
        comma,
        period,
        slash,
        caps_lock,
        f1,
        f2,
        f3,
        f4,
        f5,
        f6,
        f7,
        f8,
        f9,
        f10,
        f11,
        f12,
        f13,
        f14,
        f15,
        f16,
        f17,
        f18,
        f19,
        f20,
        f21,
        f22,
        f23,
        f24,
        print_screen,
        scroll_lock,
        pause,
        insert,
        home,
        page_up,
        del,
        end,
        page_down,
        right,
        left,
        down,
        up,
        num_lock,
        num_divide,
        num_multiply,
        num_minus,
        num_plus,
        num_enter,
        num_1,
        num_2,
        num_3,
        num_4,
        num_5,
        num_6,
        num_7,
        num_8,
        num_9,
        num_0,
        num_period,
        non_us_backslash,
        left_control,
        left_shift,
        left_alt,
        left_gui,
        right_control,
        right_shift,
        right_alt,
        right_gui,

        count
    };

    bool key_down(Key key);
    bool key_up(Key key);
    bool key_press(Key key);
    bool key_release(Key key);
}

#endif /* KAI_KEYBOARD_H */
